# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FiberGISDesigner
                                 A QGIS plugin
 QGIS plugin for intelligent telecom infrastructure design, route planning, facility placement and BOM export.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-05-19
        copyright            : (C) 2026 by 柯楚涵/武汉工程大学
        email                : 852339013@qq.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load FiberGISDesigner class from file FiberGISDesigner.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .fibergis_designer import FiberGISDesigner
    return FiberGISDesigner(iface)
