# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FiberGISDesigner
                                 A QGIS plugin
 QGIS plugin for intelligent telecom infrastructure design, route planning, facility placement and BOM export.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-05-19
        git sha              : $Format:%H$
        copyright            : (C) 2026 by 柯楚涵/武汉工程大学
        email                : 852339013@qq.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .fibergis_designer_dialog import FiberGISDesignerDialog
import os.path
import csv

from qgis.PyQt.QtWidgets import QMessageBox
from qgis.core import (
    QgsProject,
    QgsVectorLayer,
    QgsFeature,
    QgsGeometry,
    QgsPointXY,
    QgsField,
    QgsWkbTypes
)
from PyQt5.QtCore import QVariant



class FiberGISDesigner:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'FiberGISDesigner_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&FiberGIS Designer')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('FiberGISDesigner', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/fibergis_designer/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Start Telecom Design'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&FiberGIS Designer'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = FiberGISDesignerDialog()

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            self.create_demo_telecom_design()
    
    def create_demo_telecom_design(self):
        """Create a demo telecom design with nodes and a cable line."""

        project = QgsProject.instance()

        # 1. Create telecom node layer
        node_layer = QgsVectorLayer(
            "Point?crs=EPSG:4326",
            "通信节点_demo",
            "memory"
        )
        node_provider = node_layer.dataProvider()
        node_provider.addAttributes([
            QgsField("name", QVariant.String),
            QgsField("type", QVariant.String),
            QgsField("status", QVariant.String)
        ])
        node_layer.updateFields()

        # 2. Create two demo nodes
        node_a = QgsFeature(node_layer.fields())
        node_a.setGeometry(QgsGeometry.fromPointXY(QgsPointXY(114.3000, 30.6000)))
        node_a.setAttributes(["A机房", "机房", "新建"])

        node_b = QgsFeature(node_layer.fields())
        node_b.setGeometry(QgsGeometry.fromPointXY(QgsPointXY(114.3100, 30.6050)))
        node_b.setAttributes(["B基站", "基站", "新建"])

        node_provider.addFeatures([node_a, node_b])
        node_layer.updateExtents()
        project.addMapLayer(node_layer)

        # 3. Create telecom cable line layer
        line_layer = QgsVectorLayer(
            "LineString?crs=EPSG:4326",
            "通信线路_demo",
            "memory"
        )
        line_provider = line_layer.dataProvider()
        line_provider.addAttributes([
            QgsField("name", QVariant.String),
            QgsField("cable_type", QVariant.String),
            QgsField("start_node", QVariant.String),
            QgsField("end_node", QVariant.String),
            QgsField("length_deg", QVariant.Double)
        ])
        line_layer.updateFields()

        # 4. Create demo cable line
        start_point = QgsPointXY(114.3000, 30.6000)
        end_point = QgsPointXY(114.3100, 30.6050)
        line_geom = QgsGeometry.fromPolylineXY([start_point, end_point])

        line_feature = QgsFeature(line_layer.fields())
        line_feature.setGeometry(line_geom)
        line_feature.setAttributes([
            "A机房-B基站光缆",
            "48芯光缆",
            "A机房",
            "B基站",
            line_geom.length()
        ])

        line_provider.addFeature(line_feature)
        line_layer.updateExtents()
        project.addMapLayer(line_layer)

        # 5. Create telecom facility layer and manholes along the demo cable line
        facility_layer = QgsVectorLayer(
            "Point?crs=EPSG:4326",
            "通信设施_demo",
            "memory"
        )
        facility_provider = facility_layer.dataProvider()
        facility_provider.addAttributes([
            QgsField("name", QVariant.String),
            QgsField("facility_type", QVariant.String),
            QgsField("line_name", QVariant.String),
            QgsField("seq", QVariant.Int)
        ])
        facility_layer.updateFields()

        manhole_features = []
        line_name = "A机房-B基站光缆"
        for seq in range(1, 6):
            ratio = seq / 6.0
            x = start_point.x() + (end_point.x() - start_point.x()) * ratio
            y = start_point.y() + (end_point.y() - start_point.y()) * ratio

            manhole_feature = QgsFeature(facility_layer.fields())
            manhole_feature.setGeometry(QgsGeometry.fromPointXY(QgsPointXY(x, y)))
            manhole_feature.setAttributes([
                "{}号人井".format(seq),
                "人井",
                line_name,
                seq
            ])
            manhole_features.append(manhole_feature)

        facility_provider.addFeatures(manhole_features)
        facility_layer.updateExtents()
        project.addMapLayer(facility_layer)

        # 6. Export demo BOM
        bom_path = self.export_demo_bom()

        # 7. Zoom to created layers
        self.iface.mapCanvas().setExtent(line_layer.extent())
        self.iface.mapCanvas().refresh()

        QMessageBox.information(
            self.iface.mainWindow(),
            "FiberGIS Designer",
            "已生成示例通信设计：2个通信节点、1条通信线路、5个人井，并导出 BOM。\n"
            "BOM路径：{}".format(bom_path)
        )

    def export_demo_bom(self):
        """Export a demo BOM CSV file for the generated telecom design."""

        output_dir = os.path.join(self.plugin_dir, "output")
        os.makedirs(output_dir, exist_ok=True)

        bom_path = os.path.join(output_dir, "bom_demo.csv")
        rows = [
            ["物料名称", "规格型号", "单位", "数量", "计算依据"],
            ["光缆", "48芯光缆", "段", 1, "A机房-B基站光缆"],
            ["通信节点", "机房", "个", 1, "A机房"],
            ["通信节点", "基站", "个", 1, "B基站"],
            ["人井", "标准人井", "个", 5, "沿线路自动布设"]
        ]

        with open(bom_path, "w", newline="", encoding="utf-8-sig") as bom_file:
            writer = csv.writer(bom_file)
            writer.writerows(rows)

        return bom_path
