# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FiberGISDesigner
                                 A QGIS plugin
 QGIS plugin for intelligent telecom infrastructure design, route planning, facility placement and BOM export.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-05-19
        git sha              : $Format:%H$
        copyright            : (C) 2026 by 柯楚涵/武汉工程大学
        email                : 852339013@qq.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .fibergis_designer_dialog import FiberGISDesignerDialog
import os.path
import csv
import json
import re
from datetime import datetime

try:
    import requests
except ImportError:
    requests = None

from qgis.PyQt import QtWidgets
from qgis.PyQt.QtWidgets import QMessageBox
from qgis.core import (
    QgsProject,
    QgsVectorLayer,
    QgsFeature,
    QgsGeometry,
    QgsPointXY,
    QgsField,
    QgsDistanceArea,
    QgsCoordinateReferenceSystem,
    QgsWkbTypes
)
from PyQt5.QtCore import QVariant



class FiberGISDesigner:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'FiberGISDesigner_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&FiberGIS Designer')
        self.ai_configs_path = os.path.join(self.plugin_dir, "ai_configs.json")
        self.ai_configs = self.load_ai_configs()

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('FiberGISDesigner', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/fibergis_designer/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Start Telecom Design'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&FiberGIS Designer'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = FiberGISDesignerDialog()
            self.dlg.aiSettingsButton.setAutoDefault(False)
            self.dlg.aiSettingsButton.setDefault(False)
            self.dlg.aiSettingsButton.clicked.connect(self.open_ai_settings_dialog)

        self.ai_configs = self.load_ai_configs()
        self.refresh_ai_provider_combo()
        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            start_name = self.dlg.startNameLineEdit.text().strip() or "A机房"
            end_name = self.dlg.endNameLineEdit.text().strip() or "B基站"
            cable_type = self.dlg.cableTypeLineEdit.text().strip() or "48芯光缆"
            manhole_count = max(0, self.dlg.manholeCountSpinBox.value())
            generation_mode = "ai" if self.dlg.aiModeRadioButton.isChecked() else "traditional"
            ai_config = self.get_selected_ai_config() if generation_mode == "ai" else None

            self.create_demo_telecom_design(
                start_name,
                end_name,
                cable_type,
                manhole_count,
                generation_mode,
                ai_config
            )
    
    def create_demo_telecom_design(
        self,
        start_name="A机房",
        end_name="B基站",
        cable_type="48芯光缆",
        manhole_count=5,
        generation_mode="traditional",
        ai_config=None
    ):
        """Create a demo telecom design with nodes and a cable line."""

        start_name = start_name.strip() or "A机房"
        end_name = end_name.strip() or "B基站"
        cable_type = cable_type.strip() or "48芯光缆"
        manhole_count = max(0, int(manhole_count))
        line_name = "{}-{}光缆".format(start_name, end_name)
        generation_mode = "ai" if generation_mode == "ai" else "traditional"
        mode_label = "AI模式（智能规划）" if generation_mode == "ai" else "传统模式（直线生成）"

        project = QgsProject.instance()
        start_point = QgsPointXY(114.3000, 30.6000)
        end_point = QgsPointXY(114.3100, 30.6050)
        route_points = [start_point, end_point]
        ai_provider_name = "未使用"
        ai_model_name = "未使用"
        ai_status = "传统直线生成"

        if generation_mode == "ai":
            ai_provider_name = ai_config.get("name", "未配置") if ai_config else "未配置"
            ai_model_name = ai_config.get("model", "未配置") if ai_config else "未配置"
            try:
                route_points, ai_status = self.get_ai_route_points(
                    start_name,
                    end_name,
                    cable_type,
                    manhole_count,
                    start_point,
                    end_point,
                    ai_config
                )
            except Exception as error:
                ai_status = "AI调用失败，已回退传统直线。"
                error_message = "AI线路生成失败：{}".format(error)
                error_log_path = self.write_ai_error_log(
                    error_message,
                    {
                        "platform": ai_provider_name,
                        "model": ai_model_name,
                        "url": self.build_ai_url(
                            ai_config.get("base_url", "") if ai_config else "",
                            ai_config.get("endpoint", "") if ai_config else ""
                        ),
                        "exception": repr(error)
                    }
                )
                QMessageBox.warning(
                    self.iface.mainWindow(),
                    "FiberGIS Designer",
                    "{}\n已回退传统直线生成。\n错误日志：{}".format(
                        error_message,
                        error_log_path
                    )
                )

        # 1. Create telecom node layer
        node_layer = QgsVectorLayer(
            "Point?crs=EPSG:4326",
            "通信节点_demo",
            "memory"
        )
        node_provider = node_layer.dataProvider()
        node_provider.addAttributes([
            QgsField("name", QVariant.String),
            QgsField("type", QVariant.String),
            QgsField("status", QVariant.String)
        ])
        node_layer.updateFields()

        # 2. Create two demo nodes
        node_a = QgsFeature(node_layer.fields())
        node_a.setGeometry(QgsGeometry.fromPointXY(QgsPointXY(114.3000, 30.6000)))
        node_a.setAttributes([start_name, "机房", "新建"])

        node_b = QgsFeature(node_layer.fields())
        node_b.setGeometry(QgsGeometry.fromPointXY(QgsPointXY(114.3100, 30.6050)))
        node_b.setAttributes([end_name, "基站", "新建"])

        node_provider.addFeatures([node_a, node_b])
        node_layer.updateExtents()
        project.addMapLayer(node_layer)

        # 3. Create telecom cable line layer
        line_layer = QgsVectorLayer(
            "LineString?crs=EPSG:4326",
            "通信线路_demo",
            "memory"
        )
        line_provider = line_layer.dataProvider()
        line_provider.addAttributes([
            QgsField("name", QVariant.String),
            QgsField("cable_type", QVariant.String),
            QgsField("start_node", QVariant.String),
            QgsField("end_node", QVariant.String),
            QgsField("length_deg", QVariant.Double),
            QgsField("length_m", QVariant.Double)
        ])
        line_layer.updateFields()

        # 4. Create demo cable line
        line_geom = QgsGeometry.fromPolylineXY(route_points)
        length_m = self.calculate_route_length_m(route_points, project)

        line_feature = QgsFeature(line_layer.fields())
        line_feature.setGeometry(line_geom)
        line_feature.setAttributes([
            line_name,
            cable_type,
            start_name,
            end_name,
            line_geom.length(),
            length_m
        ])

        line_provider.addFeature(line_feature)
        line_layer.updateExtents()
        project.addMapLayer(line_layer)

        # 5. Create telecom facility layer and manholes along the demo cable line
        facility_layer = QgsVectorLayer(
            "Point?crs=EPSG:4326",
            "通信设施_demo",
            "memory"
        )
        facility_provider = facility_layer.dataProvider()
        facility_provider.addAttributes([
            QgsField("name", QVariant.String),
            QgsField("facility_type", QVariant.String),
            QgsField("line_name", QVariant.String),
            QgsField("seq", QVariant.Int)
        ])
        facility_layer.updateFields()

        manhole_features = []
        for seq in range(1, manhole_count + 1):
            ratio = seq / (manhole_count + 1.0)
            manhole_point = self.interpolate_point_on_route(route_points, ratio)

            manhole_feature = QgsFeature(facility_layer.fields())
            manhole_feature.setGeometry(QgsGeometry.fromPointXY(manhole_point))
            manhole_feature.setAttributes([
                "{}号人井".format(seq),
                "人井",
                line_name,
                seq
            ])
            manhole_features.append(manhole_feature)

        if manhole_features:
            facility_provider.addFeatures(manhole_features)
        facility_layer.updateExtents()
        project.addMapLayer(facility_layer)

        # 6. Export demo BOM
        bom_path = self.export_demo_bom(
            start_name,
            end_name,
            cable_type,
            manhole_count,
            length_m
        )

        # 7. Run demo rule check
        risk_report_path = self.run_demo_rule_check(
            start_name,
            end_name,
            manhole_count,
            bom_path
        )

        # 8. Zoom to created layers
        self.iface.mapCanvas().setExtent(line_layer.extent())
        self.iface.mapCanvas().refresh()

        QMessageBox.information(
            self.iface.mainWindow(),
            "FiberGIS Designer",
            "已生成示例通信设计：\n"
            "起点：{}\n"
            "终点：{}\n"
            "光缆型号：{}\n"
            "生成模式：{}\n"
            "线路长度：{} 米\n"
            "人井数量：{}\n"
            "AI平台：{}\n"
            "AI模型：{}\n"
            "AI状态：{}\n"
            "BOM路径：{}\n"
            "审查报告路径：{}".format(
                start_name,
                end_name,
                cable_type,
                mode_label,
                length_m,
                manhole_count,
                ai_provider_name,
                ai_model_name,
                ai_status,
                bom_path,
                risk_report_path
            )
        )

    def load_ai_configs(self):
        """Load AI platform configurations from the local JSON file."""

        if not os.path.exists(self.ai_configs_path):
            return []

        try:
            with open(self.ai_configs_path, "r", encoding="utf-8") as config_file:
                data = json.load(config_file)
        except (OSError, ValueError):
            return []

        if isinstance(data, dict):
            if isinstance(data.get("platforms"), list):
                configs = data.get("platforms")
            elif any(key in data for key in ("name", "base_url", "api_key", "model")):
                configs = [data]
            else:
                configs = []
        else:
            configs = data
        if not isinstance(configs, list):
            return []

        normalized_configs = []
        for config in configs:
            if not isinstance(config, dict):
                continue

            request_json = config.get("request_json", config.get("config_json", {}))
            if isinstance(request_json, str):
                try:
                    request_json = json.loads(request_json) if request_json.strip() else {}
                except ValueError:
                    request_json = {}
            if not isinstance(request_json, dict):
                request_json = {}

            base_url = config.get("base_url", "").strip()
            endpoint = config.get("endpoint", "").strip()
            legacy_request_url = config.get("request_url", "").strip()
            if not base_url and legacy_request_url:
                base_url = legacy_request_url
                endpoint = ""

            normalized_configs.append({
                "name": config.get("name", config.get("provider_name", "")).strip(),
                "base_url": base_url,
                "endpoint": endpoint,
                "api_key": config.get("api_key", "").strip(),
                "model": config.get("model", "").strip(),
                "request_json": request_json
            })

        return normalized_configs

    def save_ai_configs(self):
        """Save AI platform configurations to the local JSON file."""

        data = {"platforms": self.ai_configs}
        with open(self.ai_configs_path, "w", encoding="utf-8") as config_file:
            json.dump(data, config_file, ensure_ascii=False, indent=2)

        return self.ai_configs_path

    def refresh_ai_provider_combo(self):
        """Refresh the AI platform combo box in the main plugin dialog."""

        if not hasattr(self, "dlg") or not hasattr(self.dlg, "aiProviderComboBox"):
            return

        combo_box = self.dlg.aiProviderComboBox
        combo_box.clear()
        if not self.ai_configs:
            combo_box.addItem("未配置AI平台", -1)
            combo_box.setEnabled(False)
            return

        combo_box.setEnabled(True)
        for index, config in enumerate(self.ai_configs):
            provider_name = config.get("name") or "未命名平台"
            model = config.get("model") or "未设置模型"
            combo_box.addItem("{} / {}".format(provider_name, model), index)

    def get_selected_ai_config(self):
        """Return the AI platform configuration selected in the main dialog."""

        if not hasattr(self, "dlg") or not hasattr(self.dlg, "aiProviderComboBox"):
            return None

        index = self.dlg.aiProviderComboBox.currentData()
        if index is None or index < 0 or index >= len(self.ai_configs):
            return None

        return self.ai_configs[index]

    def open_ai_settings_dialog(self):
        """Open the AI platform configuration dialog."""

        parent_dialog = self.dlg if hasattr(self, "dlg") and self.dlg is not None else self.iface.mainWindow()
        if hasattr(self, "dlg") and self.dlg is not None:
            self.dlg.show()

        dialog = QtWidgets.QDialog(parent_dialog)
        dialog.setWindowTitle("AI 设置")
        dialog.resize(760, 480)
        dialog.setModal(True)
        dialog.working_ai_configs = [
            dict(config, request_json=dict(config.get("request_json", {})))
            for config in self.ai_configs
        ]

        main_layout = QtWidgets.QHBoxLayout(dialog)
        left_layout = QtWidgets.QVBoxLayout()
        right_layout = QtWidgets.QVBoxLayout()

        dialog.providerListWidget = QtWidgets.QListWidget(dialog)
        left_layout.addWidget(QtWidgets.QLabel("AI 平台", dialog))
        left_layout.addWidget(dialog.providerListWidget)

        list_button_layout = QtWidgets.QHBoxLayout()
        dialog.newConfigButton = QtWidgets.QPushButton("新增", dialog)
        dialog.deleteConfigButton = QtWidgets.QPushButton("删除", dialog)
        list_button_layout.addWidget(dialog.newConfigButton)
        list_button_layout.addWidget(dialog.deleteConfigButton)
        left_layout.addLayout(list_button_layout)

        form_layout = QtWidgets.QFormLayout()
        dialog.providerNameLineEdit = QtWidgets.QLineEdit(dialog)
        dialog.officialUrlLineEdit = QtWidgets.QLineEdit(dialog)
        dialog.apiKeyLineEdit = QtWidgets.QLineEdit(dialog)
        dialog.apiKeyLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        dialog.requestUrlLineEdit = QtWidgets.QLineEdit(dialog)
        dialog.modelLineEdit = QtWidgets.QLineEdit(dialog)
        dialog.configJsonTextEdit = QtWidgets.QTextEdit(dialog)
        dialog.configJsonTextEdit.setPlaceholderText('例如：{"temperature": 0.2, "max_tokens": 1024, "timeout": 10}')

        form_layout.addRow("平台名称", dialog.providerNameLineEdit)
        form_layout.addRow("基础 URL", dialog.officialUrlLineEdit)
        form_layout.addRow("API Key", dialog.apiKeyLineEdit)
        form_layout.addRow("API 路径", dialog.requestUrlLineEdit)
        form_layout.addRow("模型名称", dialog.modelLineEdit)
        form_layout.addRow("请求 JSON", dialog.configJsonTextEdit)
        right_layout.addLayout(form_layout)

        action_layout = QtWidgets.QHBoxLayout()
        dialog.saveConfigButton = QtWidgets.QPushButton("保存配置", dialog)
        dialog.closeConfigButton = QtWidgets.QPushButton("关闭", dialog)
        action_layout.addStretch()
        action_layout.addWidget(dialog.saveConfigButton)
        action_layout.addWidget(dialog.closeConfigButton)
        right_layout.addLayout(action_layout)

        main_layout.addLayout(left_layout, 1)
        main_layout.addLayout(right_layout, 2)

        dialog.providerListWidget.currentRowChanged.connect(
            lambda row: self.fill_ai_settings_form(dialog, row)
        )
        dialog.newConfigButton.clicked.connect(lambda: self.new_ai_settings_config(dialog))
        dialog.deleteConfigButton.clicked.connect(lambda: self.delete_ai_settings_config(dialog))
        dialog.saveConfigButton.clicked.connect(lambda: self.save_ai_settings_config(dialog))
        dialog.closeConfigButton.clicked.connect(dialog.accept)

        self.populate_ai_settings_list(dialog)
        if dialog.working_ai_configs:
            dialog.providerListWidget.setCurrentRow(0)
        else:
            self.clear_ai_settings_form(dialog)

        dialog.exec_()
        self.ai_configs = self.load_ai_configs()
        self.refresh_ai_provider_combo()
        if hasattr(self, "dlg") and self.dlg is not None:
            self.dlg.show()
            self.dlg.raise_()
            self.dlg.activateWindow()

    def populate_ai_settings_list(self, dialog):
        """Populate the AI settings list widget from the dialog working copy."""

        dialog.providerListWidget.blockSignals(True)
        dialog.providerListWidget.clear()
        for config in dialog.working_ai_configs:
            provider_name = config.get("name") or "未命名平台"
            model = config.get("model") or "未设置模型"
            dialog.providerListWidget.addItem("{} / {}".format(provider_name, model))
        dialog.providerListWidget.blockSignals(False)

    def fill_ai_settings_form(self, dialog, row):
        """Fill AI settings form controls from a selected config row."""

        if row < 0 or row >= len(dialog.working_ai_configs):
            self.clear_ai_settings_form(dialog)
            return

        config = dialog.working_ai_configs[row]
        dialog.providerNameLineEdit.setText(config.get("name", ""))
        dialog.officialUrlLineEdit.setText(config.get("base_url", ""))
        dialog.apiKeyLineEdit.setText(config.get("api_key", ""))
        dialog.requestUrlLineEdit.setText(config.get("endpoint", ""))
        dialog.modelLineEdit.setText(config.get("model", ""))
        dialog.configJsonTextEdit.setPlainText(
            json.dumps(config.get("request_json", {}), ensure_ascii=False, indent=2)
        )

    def clear_ai_settings_form(self, dialog):
        """Clear AI settings form controls."""

        dialog.providerNameLineEdit.clear()
        dialog.officialUrlLineEdit.clear()
        dialog.apiKeyLineEdit.clear()
        dialog.requestUrlLineEdit.clear()
        dialog.modelLineEdit.clear()
        dialog.configJsonTextEdit.setPlainText("{}")

    def new_ai_settings_config(self, dialog):
        """Prepare the AI settings form for a new platform config."""

        dialog.providerListWidget.clearSelection()
        dialog.providerListWidget.setCurrentRow(-1)
        self.clear_ai_settings_form(dialog)

    def delete_ai_settings_config(self, dialog):
        """Delete the selected AI platform config from the working copy."""

        row = dialog.providerListWidget.currentRow()
        if row < 0 or row >= len(dialog.working_ai_configs):
            return

        del dialog.working_ai_configs[row]
        self.ai_configs = dialog.working_ai_configs
        self.save_ai_configs()
        self.populate_ai_settings_list(dialog)
        if dialog.working_ai_configs:
            dialog.providerListWidget.setCurrentRow(min(row, len(dialog.working_ai_configs) - 1))
        else:
            self.clear_ai_settings_form(dialog)
        self.refresh_ai_provider_combo()

    def save_ai_settings_config(self, dialog):
        """Save the current AI platform form into the working copy and JSON file."""

        platform_name = dialog.providerNameLineEdit.text().strip()
        if not platform_name:
            QMessageBox.warning(dialog, "AI 设置", "请填写平台名称。")
            return

        request_json_text = dialog.configJsonTextEdit.toPlainText().strip() or "{}"
        try:
            request_json = json.loads(request_json_text)
        except ValueError as error:
            QMessageBox.warning(dialog, "AI 设置", "请求 JSON 格式不正确：{}".format(error))
            return

        if not isinstance(request_json, dict):
            QMessageBox.warning(dialog, "AI 设置", "请求 JSON 必须是一个 JSON 对象。")
            return

        config = {
            "name": platform_name,
            "base_url": dialog.officialUrlLineEdit.text().strip(),
            "endpoint": dialog.requestUrlLineEdit.text().strip(),
            "api_key": dialog.apiKeyLineEdit.text().strip(),
            "model": dialog.modelLineEdit.text().strip(),
            "request_json": request_json
        }

        row = dialog.providerListWidget.currentRow()
        if row < 0 or row >= len(dialog.working_ai_configs):
            dialog.working_ai_configs.append(config)
            row = len(dialog.working_ai_configs) - 1
        else:
            dialog.working_ai_configs[row] = config

        self.ai_configs = dialog.working_ai_configs
        self.save_ai_configs()
        self.populate_ai_settings_list(dialog)
        dialog.providerListWidget.setCurrentRow(row)
        self.refresh_ai_provider_combo()
        QMessageBox.information(dialog, "AI 设置", "AI 配置已保存。")

    def collect_map_constraints(self):
        """Collect a compact summary of available map layers as AI route constraints."""

        constraints = []
        for layer in QgsProject.instance().mapLayers().values():
            if not hasattr(layer, "wkbType"):
                continue
            extent = layer.extent()
            constraints.append({
                "name": layer.name(),
                "geometry": QgsWkbTypes.displayString(layer.wkbType()),
                "feature_count": layer.featureCount() if hasattr(layer, "featureCount") else None,
                "extent": [
                    round(extent.xMinimum(), 6),
                    round(extent.yMinimum(), 6),
                    round(extent.xMaximum(), 6),
                    round(extent.yMaximum(), 6)
                ]
            })

        return constraints

    def get_output_dir(self):
        """Return the plugin output directory, creating it when needed."""

        output_dir = os.path.join(self.plugin_dir, "output")
        os.makedirs(output_dir, exist_ok=True)
        return output_dir

    def write_ai_error_log(self, message, detail=None):
        """Append AI failure details to output/ai_error.log."""

        output_dir = self.get_output_dir()
        log_path = os.path.join(output_dir, "ai_error.log")
        detail = detail or {}
        platform_name = detail.get("platform") or detail.get("platform_name") or "未选择平台"
        url = detail.get("url") or ""
        status_code = detail.get("status_code")
        response_text = detail.get("response_text") or ""
        exception_text = detail.get("exception") or ""

        log_text = (
            "[{timestamp}]\n"
            "平台名称：{platform}\n"
            "URL：{url}\n"
            "HTTP状态码：{status_code}\n"
            "错误信息：{message}\n"
            "响应文本：{response_text}\n"
            "Python异常：{exception_text}\n\n"
        ).format(
            timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            platform=platform_name,
            url=url,
            status_code=status_code if status_code is not None else "",
            message=message,
            response_text=response_text[:2000],
            exception_text=exception_text
        )

        with open(log_path, "a", encoding="utf-8") as log_file:
            log_file.write(log_text)

        return log_path

    def log_ai_error(self, message, platform_config=None):
        """Backward-compatible wrapper for older AI error logging calls."""

        detail = {"exception": message}
        if isinstance(platform_config, dict):
            detail.update({
                "platform": platform_config.get("name", "未选择平台"),
                "url": self.build_ai_url(
                    platform_config.get("base_url", ""),
                    platform_config.get("endpoint", "")
                )
            })
        return self.write_ai_error_log(message, detail)

    def get_ai_route_points(
        self,
        start_name,
        end_name,
        cable_type,
        manhole_count,
        start_point,
        end_point,
        ai_config
    ):
        """Call the selected AI platform and return a route point sequence."""

        if not ai_config:
            raise RuntimeError("未选择有效的 AI 平台配置")

        raw_points = self.call_ai_route_planner(
            ai_config,
            start_name,
            end_name,
            cable_type,
            manhole_count
        )
        route_points = self.normalize_route_points(raw_points, start_point, end_point)
        if len(route_points) < 2:
            raise RuntimeError("AI 返回的有效线路点少于 2 个")

        return route_points, "AI线路生成成功"

    def build_ai_route_messages(
        self,
        start_name,
        end_name,
        cable_type,
        manhole_count,
        start_point,
        end_point
    ):
        """Build DeepSeek-compatible chat messages for AI route planning."""

        user_prompt = (
            "请根据以下通信设计参数生成智能线路，并严格返回 JSON 对象。\n"
            "起点名称：{start_name}\n"
            "终点名称：{end_name}\n"
            "光缆型号：{cable_type}\n"
            "人井数量：{manhole_count}\n"
            "起点坐标：[114.3000, 30.6000]\n"
            "终点坐标：[114.3100, 30.6050]\n"
            "返回格式必须为：\n"
            "{{\n"
            "  \"points\": [\n"
            "    [114.3000, 30.6000],\n"
            "    [114.3030, 30.6020],\n"
            "    [114.3060, 30.6035],\n"
            "    [114.3100, 30.6050]\n"
            "  ],\n"
            "  \"reason\": \"线路规划理由\",\n"
            "  \"risk_notes\": [\"风险提示1\", \"风险提示2\"]\n"
            "}}\n"
            "points 必须至少包含起点和终点，每个 point 必须是 [lon, lat] 两个数字。"
            "不要返回 ```json 代码块。"
        ).format(
            start_name=start_name,
            end_name=end_name,
            cable_type=cable_type,
            manhole_count=manhole_count
        )

        return [
            {
                "role": "system",
                "content": "你是通信基建 GIS 智能设计助手，只能输出合法 JSON，不要输出 Markdown，不要输出解释性文字。"
            },
            {"role": "user", "content": user_prompt}
        ]

    def call_ai_route_planner(self, platform_config, start_name, end_name, cable_type, manhole_count):
        """Call DeepSeek-compatible Chat Completions API and return route points."""

        start_point = QgsPointXY(114.3000, 30.6000)
        end_point = QgsPointXY(114.3100, 30.6050)
        messages = self.build_ai_route_messages(
            start_name,
            end_name,
            cable_type,
            manhole_count,
            start_point,
            end_point
        )
        response_json = self.call_ai(platform_config, messages)
        content = self.extract_chat_completion_content(response_json)
        parsed_content = self.parse_json_from_ai_text(content)
        if not isinstance(parsed_content, dict):
            raise RuntimeError("AI返回内容不是合法 JSON 对象。")

        points = parsed_content.get("points")
        if not self.is_point_list(points):
            raise RuntimeError("AI返回内容中未找到有效 points 字段。")

        return points

    def call_ai(self, platform_config, messages):
        """Call DeepSeek/OpenAI-compatible Chat Completions API with requests.post."""

        if requests is None:
            raise RuntimeError("当前 Python 环境未安装 requests 库")

        if not isinstance(platform_config, dict):
            raise RuntimeError("AI 平台配置无效")

        platform_name = platform_config.get("name", "DeepSeek") or "DeepSeek"
        base_url = platform_config.get("base_url", "https://api.deepseek.com").strip()
        endpoint = platform_config.get("endpoint", "/chat/completions").strip()
        api_key = platform_config.get("api_key", "").strip()
        model = platform_config.get("model", "deepseek-chat").strip() or "deepseek-chat"
        request_json = platform_config.get("request_json", {})
        if not isinstance(request_json, dict):
            request_json = {}

        if not base_url:
            base_url = "https://api.deepseek.com"
        if not api_key:
            raise RuntimeError("{} 的 API Key 为空".format(platform_name))

        url = self.build_ai_url(base_url, endpoint)
        payload_options = dict(request_json)
        timeout = payload_options.pop("timeout", 10)
        extra_headers = payload_options.pop("headers", {})
        body_options = payload_options.pop("body", {})

        payload = {
            "model": model,
            "messages": messages,
            "stream": False
        }
        payload.update(payload_options)
        if isinstance(body_options, dict):
            payload.update(body_options)
        payload.setdefault("temperature", 0.1)
        payload.setdefault("max_tokens", 1000)
        payload.setdefault("response_format", {"type": "json_object"})

        headers = {
            "Authorization": "Bearer {}".format(api_key),
            "Content-Type": "application/json"
        }
        if isinstance(extra_headers, dict):
            headers.update(extra_headers)

        response = None
        try:
            response = requests.post(
                url,
                headers=headers,
                json=payload,
                timeout=float(timeout)
            )
            response.raise_for_status()
            return response.json()
        except requests.exceptions.RequestException as error:
            status_code = response.status_code if response is not None else None
            response_text = response.text if response is not None else ""
            log_path = self.write_ai_error_log(
                "{} 请求失败：{}".format(platform_name, error),
                {
                    "platform": platform_name,
                    "url": url,
                    "status_code": status_code,
                    "response_text": response_text,
                    "exception": repr(error)
                }
            )
            raise RuntimeError("{} 请求失败，详见日志：{}".format(platform_name, log_path))
        except ValueError as error:
            response_text = response.text if response is not None else ""
            log_path = self.write_ai_error_log(
                "{} 返回内容不是有效 JSON".format(platform_name),
                {
                    "platform": platform_name,
                    "url": url,
                    "status_code": response.status_code if response is not None else None,
                    "response_text": response_text,
                    "exception": repr(error)
                }
            )
            raise RuntimeError("{} 返回内容不是有效 JSON，详见日志：{}".format(platform_name, log_path))

    def build_ai_url(self, base_url, endpoint):
        """Build final AI API URL from base_url and endpoint."""

        base_url = (base_url or "https://api.deepseek.com").strip()
        endpoint = (endpoint or "/chat/completions").strip()
        return "{}/{}".format(base_url.rstrip("/"), endpoint.lstrip("/"))

    def build_ai_request_url(self, base_url, endpoint):
        """Backward-compatible wrapper for AI URL building."""

        return self.build_ai_url(base_url, endpoint)

    def extract_chat_completion_content(self, response_json):
        """Extract message.content from a Chat Completions response."""

        try:
            return response_json["choices"][0]["message"]["content"]
        except (KeyError, IndexError, TypeError):
            raise RuntimeError("AI返回内容中未找到 choices[0].message.content。")

    def find_ai_point_sequence(self, data):
        """Find a route point sequence in common AI response shapes."""

        if isinstance(data, dict):
            for key in ("points", "route_points", "route", "coordinates", "path", "polyline"):
                if key in data:
                    points = self.find_ai_point_sequence(data[key])
                    if points:
                        return points

            choices = data.get("choices")
            if isinstance(choices, list) and choices:
                message = choices[0].get("message", {}) if isinstance(choices[0], dict) else {}
                content = message.get("content", "")
                parsed_content = self.parse_json_from_ai_text(content)
                if parsed_content is not None:
                    return self.find_ai_point_sequence(parsed_content)

            for value in data.values():
                points = self.find_ai_point_sequence(value)
                if points:
                    return points

        if isinstance(data, list):
            if self.is_point_list(data):
                return data
            for item in data:
                points = self.find_ai_point_sequence(item)
                if points:
                    return points

        if isinstance(data, str):
            parsed_text = self.parse_json_from_ai_text(data)
            if parsed_text is not None:
                return self.find_ai_point_sequence(parsed_text)

        return []

    def parse_json_from_ai_text(self, text):
        """Parse JSON from plain text or fenced AI response content."""

        if not text:
            return None

        try:
            return json.loads(text)
        except ValueError:
            pass

        fence_match = re.search(r"```(?:json)?\s*(.*?)```", text, re.S)
        if fence_match:
            try:
                return json.loads(fence_match.group(1).strip())
            except ValueError:
                pass

        object_start = text.find("{")
        object_end = text.rfind("}")
        if object_start >= 0 and object_end > object_start:
            try:
                return json.loads(text[object_start:object_end + 1])
            except ValueError:
                pass

        array_start = text.find("[")
        array_end = text.rfind("]")
        if array_start >= 0 and array_end > array_start:
            try:
                return json.loads(text[array_start:array_end + 1])
            except ValueError:
                pass

        return None

    def is_point_list(self, data):
        """Return True when a list appears to contain coordinate points."""

        if not data:
            return False

        first_item = data[0]
        if isinstance(first_item, (list, tuple)) and len(first_item) >= 2:
            return True
        if isinstance(first_item, dict):
            return any(key in first_item for key in ("lon", "lng", "x")) and any(
                key in first_item for key in ("lat", "y")
            )

        return False

    def normalize_route_points(self, raw_points, start_point, end_point):
        """Normalize AI route coordinates into a QgsPointXY list."""

        route_points = []
        for item in raw_points or []:
            point = None
            if isinstance(item, (list, tuple)) and len(item) >= 2:
                point = self.safe_qgs_point(item[0], item[1])
            elif isinstance(item, dict):
                lon = item.get("lon", item.get("lng", item.get("x")))
                lat = item.get("lat", item.get("y"))
                point = self.safe_qgs_point(lon, lat)
            if point:
                route_points.append(point)

        if len(route_points) < 2:
            return []

        if self.point_distance_deg(route_points[0], start_point) > 0.000001:
            route_points.insert(0, start_point)
        else:
            route_points[0] = start_point

        if self.point_distance_deg(route_points[-1], end_point) > 0.000001:
            route_points.append(end_point)
        else:
            route_points[-1] = end_point

        return route_points

    def safe_qgs_point(self, lon, lat):
        """Create a QgsPointXY only when coordinates are numeric and plausible."""

        try:
            lon = float(lon)
            lat = float(lat)
        except (TypeError, ValueError):
            return None

        if lon < -180 or lon > 180 or lat < -90 or lat > 90:
            return None

        return QgsPointXY(lon, lat)

    def point_distance_deg(self, point_a, point_b):
        """Calculate a simple degree-space distance between two points."""

        dx = point_a.x() - point_b.x()
        dy = point_a.y() - point_b.y()
        return (dx * dx + dy * dy) ** 0.5

    def calculate_route_length_m(self, route_points, project):
        """Calculate a WGS84 ellipsoid route length in meters."""

        distance_area = QgsDistanceArea()
        distance_area.setSourceCrs(
            QgsCoordinateReferenceSystem("EPSG:4326"),
            project.transformContext()
        )
        distance_area.setEllipsoid("WGS84")

        length_m = 0.0
        for index in range(len(route_points) - 1):
            length_m += distance_area.measureLine(route_points[index], route_points[index + 1])

        return round(length_m, 2)

    def interpolate_point_on_route(self, route_points, ratio):
        """Interpolate a point along a route using degree-space segment lengths."""

        if not route_points:
            return QgsPointXY(114.3000, 30.6000)
        if len(route_points) == 1:
            return route_points[0]

        ratio = max(0.0, min(1.0, float(ratio)))
        segment_lengths = []
        total_length = 0.0
        for index in range(len(route_points) - 1):
            segment_length = self.point_distance_deg(route_points[index], route_points[index + 1])
            segment_lengths.append(segment_length)
            total_length += segment_length

        if total_length == 0:
            return route_points[0]

        target_length = total_length * ratio
        traversed_length = 0.0
        for index, segment_length in enumerate(segment_lengths):
            if traversed_length + segment_length >= target_length:
                local_ratio = (target_length - traversed_length) / segment_length if segment_length else 0
                start_point = route_points[index]
                end_point = route_points[index + 1]
                x = start_point.x() + (end_point.x() - start_point.x()) * local_ratio
                y = start_point.y() + (end_point.y() - start_point.y()) * local_ratio
                return QgsPointXY(x, y)
            traversed_length += segment_length

        return route_points[-1]

    def export_demo_bom(
        self,
        start_name="A机房",
        end_name="B基站",
        cable_type="48芯光缆",
        manhole_count=5,
        length_m=0
    ):
        """Export a demo BOM CSV file for the generated telecom design."""

        start_name = start_name.strip() or "A机房"
        end_name = end_name.strip() or "B基站"
        cable_type = cable_type.strip() or "48芯光缆"
        manhole_count = max(0, int(manhole_count))
        length_m = round(float(length_m), 2)
        line_name = "{}-{}光缆".format(start_name, end_name)

        output_dir = os.path.join(self.plugin_dir, "output")
        os.makedirs(output_dir, exist_ok=True)

        bom_path = os.path.join(output_dir, "bom_demo.csv")
        rows = [
            ["物料名称", "规格型号", "单位", "数量", "计算依据"],
            ["光缆", cable_type, "米", length_m, "{}长度自动计算".format(line_name)],
            ["通信节点", "机房", "个", 1, start_name],
            ["通信节点", "基站", "个", 1, end_name],
            ["人井", "标准人井", "个", manhole_count, "沿线路自动布设"]
        ]

        with open(bom_path, "w", newline="", encoding="utf-8-sig") as bom_file:
            writer = csv.writer(bom_file)
            writer.writerows(rows)

        return bom_path

    def run_demo_rule_check(
        self,
        start_name="A机房",
        end_name="B基站",
        manhole_count=5,
        bom_path=None
    ):
        """Run basic demo design checks and export a risk report CSV file."""

        start_name = start_name.strip() or "A机房"
        end_name = end_name.strip() or "B基站"
        manhole_count = max(0, int(manhole_count))
        line_name = "{}-{}光缆".format(start_name, end_name)
        bom_file_name = os.path.basename(bom_path) if bom_path else "bom_demo.csv"

        output_dir = os.path.join(self.plugin_dir, "output")
        os.makedirs(output_dir, exist_ok=True)

        risk_report_path = os.path.join(output_dir, "risk_report_demo.csv")
        rows = [
            ["审查项", "规则说明", "审查结果", "风险等级", "整改建议"],
            ["起点完整性检查", "检查是否存在{}".format(start_name), "通过", "无", "无需整改"],
            ["终点完整性检查", "检查是否存在{}".format(end_name), "通过", "无", "无需整改"],
            ["线路完整性检查", "检查是否生成{}".format(line_name), "通过", "无", "无需整改"],
            [
                "人井布设检查",
                "检查是否自动布设 {} 个人井".format(manhole_count),
                "通过",
                "无",
                "无需整改"
            ],
            ["BOM生成检查", "检查是否导出 {}".format(bom_file_name), "通过", "无", "无需整改"]
        ]

        with open(risk_report_path, "w", newline="", encoding="utf-8-sig") as report_file:
            writer = csv.writer(report_file)
            writer.writerows(rows)

        review_layer = QgsVectorLayer(
            "Point?crs=EPSG:4326",
            "设计审查_demo",
            "memory"
        )
        review_provider = review_layer.dataProvider()
        review_provider.addAttributes([
            QgsField("check_item", QVariant.String),
            QgsField("result", QVariant.String),
            QgsField("risk_level", QVariant.String),
            QgsField("suggestion", QVariant.String)
        ])
        review_layer.updateFields()

        start_point = QgsPointXY(114.3000, 30.6000)
        end_point = QgsPointXY(114.3100, 30.6050)
        midpoint = QgsPointXY(
            (start_point.x() + end_point.x()) / 2.0,
            (start_point.y() + end_point.y()) / 2.0
        )

        review_feature = QgsFeature(review_layer.fields())
        review_feature.setGeometry(QgsGeometry.fromPointXY(midpoint))
        review_feature.setAttributes([
            "基础设计审查",
            "通过",
            "无",
            "无需整改"
        ])

        review_provider.addFeature(review_feature)
        review_layer.updateExtents()
        QgsProject.instance().addMapLayer(review_layer)

        return risk_report_path
