# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FiberGISDesigner
                                 A QGIS plugin
 QGIS plugin for intelligent telecom infrastructure design, route planning, facility placement and BOM export.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-05-19
        git sha              : $Format:%H$
        copyright            : (C) 2026 by 柯楚涵/武汉工程大学
        email                : 852339013@qq.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .fibergis_designer_dialog import FiberGISDesignerDialog
import os.path
import csv

from qgis.PyQt.QtWidgets import QMessageBox
from qgis.core import (
    QgsProject,
    QgsVectorLayer,
    QgsFeature,
    QgsGeometry,
    QgsPointXY,
    QgsField,
    QgsDistanceArea,
    QgsCoordinateReferenceSystem,
    QgsWkbTypes
)
from PyQt5.QtCore import QVariant



class FiberGISDesigner:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'FiberGISDesigner_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&FiberGIS Designer')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('FiberGISDesigner', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/fibergis_designer/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Start Telecom Design'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&FiberGIS Designer'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = FiberGISDesignerDialog()

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            start_name = self.dlg.startNameLineEdit.text().strip() or "A机房"
            end_name = self.dlg.endNameLineEdit.text().strip() or "B基站"
            cable_type = self.dlg.cableTypeLineEdit.text().strip() or "48芯光缆"
            manhole_count = max(0, self.dlg.manholeCountSpinBox.value())

            self.create_demo_telecom_design(
                start_name,
                end_name,
                cable_type,
                manhole_count
            )
    
    def create_demo_telecom_design(
        self,
        start_name="A机房",
        end_name="B基站",
        cable_type="48芯光缆",
        manhole_count=5
    ):
        """Create a demo telecom design with nodes and a cable line."""

        start_name = start_name.strip() or "A机房"
        end_name = end_name.strip() or "B基站"
        cable_type = cable_type.strip() or "48芯光缆"
        manhole_count = max(0, int(manhole_count))
        line_name = "{}-{}光缆".format(start_name, end_name)

        project = QgsProject.instance()

        # 1. Create telecom node layer
        node_layer = QgsVectorLayer(
            "Point?crs=EPSG:4326",
            "通信节点_demo",
            "memory"
        )
        node_provider = node_layer.dataProvider()
        node_provider.addAttributes([
            QgsField("name", QVariant.String),
            QgsField("type", QVariant.String),
            QgsField("status", QVariant.String)
        ])
        node_layer.updateFields()

        # 2. Create two demo nodes
        node_a = QgsFeature(node_layer.fields())
        node_a.setGeometry(QgsGeometry.fromPointXY(QgsPointXY(114.3000, 30.6000)))
        node_a.setAttributes([start_name, "机房", "新建"])

        node_b = QgsFeature(node_layer.fields())
        node_b.setGeometry(QgsGeometry.fromPointXY(QgsPointXY(114.3100, 30.6050)))
        node_b.setAttributes([end_name, "基站", "新建"])

        node_provider.addFeatures([node_a, node_b])
        node_layer.updateExtents()
        project.addMapLayer(node_layer)

        # 3. Create telecom cable line layer
        line_layer = QgsVectorLayer(
            "LineString?crs=EPSG:4326",
            "通信线路_demo",
            "memory"
        )
        line_provider = line_layer.dataProvider()
        line_provider.addAttributes([
            QgsField("name", QVariant.String),
            QgsField("cable_type", QVariant.String),
            QgsField("start_node", QVariant.String),
            QgsField("end_node", QVariant.String),
            QgsField("length_deg", QVariant.Double),
            QgsField("length_m", QVariant.Double)
        ])
        line_layer.updateFields()

        # 4. Create demo cable line
        start_point = QgsPointXY(114.3000, 30.6000)
        end_point = QgsPointXY(114.3100, 30.6050)
        line_geom = QgsGeometry.fromPolylineXY([start_point, end_point])
        distance_area = QgsDistanceArea()
        distance_area.setSourceCrs(
            QgsCoordinateReferenceSystem("EPSG:4326"),
            project.transformContext()
        )
        distance_area.setEllipsoid("WGS84")
        length_m = round(distance_area.measureLine(start_point, end_point), 2)

        line_feature = QgsFeature(line_layer.fields())
        line_feature.setGeometry(line_geom)
        line_feature.setAttributes([
            line_name,
            cable_type,
            start_name,
            end_name,
            line_geom.length(),
            length_m
        ])

        line_provider.addFeature(line_feature)
        line_layer.updateExtents()
        project.addMapLayer(line_layer)

        # 5. Create telecom facility layer and manholes along the demo cable line
        facility_layer = QgsVectorLayer(
            "Point?crs=EPSG:4326",
            "通信设施_demo",
            "memory"
        )
        facility_provider = facility_layer.dataProvider()
        facility_provider.addAttributes([
            QgsField("name", QVariant.String),
            QgsField("facility_type", QVariant.String),
            QgsField("line_name", QVariant.String),
            QgsField("seq", QVariant.Int)
        ])
        facility_layer.updateFields()

        manhole_features = []
        for seq in range(1, manhole_count + 1):
            ratio = seq / (manhole_count + 1.0)
            x = start_point.x() + (end_point.x() - start_point.x()) * ratio
            y = start_point.y() + (end_point.y() - start_point.y()) * ratio

            manhole_feature = QgsFeature(facility_layer.fields())
            manhole_feature.setGeometry(QgsGeometry.fromPointXY(QgsPointXY(x, y)))
            manhole_feature.setAttributes([
                "{}号人井".format(seq),
                "人井",
                line_name,
                seq
            ])
            manhole_features.append(manhole_feature)

        if manhole_features:
            facility_provider.addFeatures(manhole_features)
        facility_layer.updateExtents()
        project.addMapLayer(facility_layer)

        # 6. Export demo BOM
        bom_path = self.export_demo_bom(
            start_name,
            end_name,
            cable_type,
            manhole_count,
            length_m
        )

        # 7. Run demo rule check
        risk_report_path = self.run_demo_rule_check(
            start_name,
            end_name,
            manhole_count,
            bom_path
        )

        # 8. Zoom to created layers
        self.iface.mapCanvas().setExtent(line_layer.extent())
        self.iface.mapCanvas().refresh()

        QMessageBox.information(
            self.iface.mainWindow(),
            "FiberGIS Designer",
            "已生成示例通信设计：\n"
            "起点：{}\n"
            "终点：{}\n"
            "光缆型号：{}\n"
            "线路长度：{} 米\n"
            "人井数量：{}\n"
            "BOM路径：{}\n"
            "审查报告路径：{}".format(
                start_name,
                end_name,
                cable_type,
                length_m,
                manhole_count,
                bom_path,
                risk_report_path
            )
        )

    def export_demo_bom(
        self,
        start_name="A机房",
        end_name="B基站",
        cable_type="48芯光缆",
        manhole_count=5,
        length_m=0
    ):
        """Export a demo BOM CSV file for the generated telecom design."""

        start_name = start_name.strip() or "A机房"
        end_name = end_name.strip() or "B基站"
        cable_type = cable_type.strip() or "48芯光缆"
        manhole_count = max(0, int(manhole_count))
        length_m = round(float(length_m), 2)
        line_name = "{}-{}光缆".format(start_name, end_name)

        output_dir = os.path.join(self.plugin_dir, "output")
        os.makedirs(output_dir, exist_ok=True)

        bom_path = os.path.join(output_dir, "bom_demo.csv")
        rows = [
            ["物料名称", "规格型号", "单位", "数量", "计算依据"],
            ["光缆", cable_type, "米", length_m, "{}长度自动计算".format(line_name)],
            ["通信节点", "机房", "个", 1, start_name],
            ["通信节点", "基站", "个", 1, end_name],
            ["人井", "标准人井", "个", manhole_count, "沿线路自动布设"]
        ]

        with open(bom_path, "w", newline="", encoding="utf-8-sig") as bom_file:
            writer = csv.writer(bom_file)
            writer.writerows(rows)

        return bom_path

    def run_demo_rule_check(
        self,
        start_name="A机房",
        end_name="B基站",
        manhole_count=5,
        bom_path=None
    ):
        """Run basic demo design checks and export a risk report CSV file."""

        start_name = start_name.strip() or "A机房"
        end_name = end_name.strip() or "B基站"
        manhole_count = max(0, int(manhole_count))
        line_name = "{}-{}光缆".format(start_name, end_name)
        bom_file_name = os.path.basename(bom_path) if bom_path else "bom_demo.csv"

        output_dir = os.path.join(self.plugin_dir, "output")
        os.makedirs(output_dir, exist_ok=True)

        risk_report_path = os.path.join(output_dir, "risk_report_demo.csv")
        rows = [
            ["审查项", "规则说明", "审查结果", "风险等级", "整改建议"],
            ["起点完整性检查", "检查是否存在{}".format(start_name), "通过", "无", "无需整改"],
            ["终点完整性检查", "检查是否存在{}".format(end_name), "通过", "无", "无需整改"],
            ["线路完整性检查", "检查是否生成{}".format(line_name), "通过", "无", "无需整改"],
            [
                "人井布设检查",
                "检查是否自动布设 {} 个人井".format(manhole_count),
                "通过",
                "无",
                "无需整改"
            ],
            ["BOM生成检查", "检查是否导出 {}".format(bom_file_name), "通过", "无", "无需整改"]
        ]

        with open(risk_report_path, "w", newline="", encoding="utf-8-sig") as report_file:
            writer = csv.writer(report_file)
            writer.writerows(rows)

        review_layer = QgsVectorLayer(
            "Point?crs=EPSG:4326",
            "设计审查_demo",
            "memory"
        )
        review_provider = review_layer.dataProvider()
        review_provider.addAttributes([
            QgsField("check_item", QVariant.String),
            QgsField("result", QVariant.String),
            QgsField("risk_level", QVariant.String),
            QgsField("suggestion", QVariant.String)
        ])
        review_layer.updateFields()

        start_point = QgsPointXY(114.3000, 30.6000)
        end_point = QgsPointXY(114.3100, 30.6050)
        midpoint = QgsPointXY(
            (start_point.x() + end_point.x()) / 2.0,
            (start_point.y() + end_point.y()) / 2.0
        )

        review_feature = QgsFeature(review_layer.fields())
        review_feature.setGeometry(QgsGeometry.fromPointXY(midpoint))
        review_feature.setAttributes([
            "基础设计审查",
            "通过",
            "无",
            "无需整改"
        ])

        review_provider.addFeature(review_feature)
        review_layer.updateExtents()
        QgsProject.instance().addMapLayer(review_layer)

        return risk_report_path
